jobs:
  test:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Install packer and ansible
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py
            pip install -r requirements.txt
            wget --quiet https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
            sudo unzip packer_1.5.5_linux_amd64.zip -d /usr/local/bin
      
      - run:
          name: Install Terraform 12
          command: |
            export TF_VERSION=0.12.29
            wget --quiet https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            sudo unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin
      - run:
          name: TF 12 Integration test
          command: make test
          no_output_timeout: 45m
      
      - run:
          name: Install Terraform 13
          command: |
            export TF_VERSION=0.13.6
            wget --quiet https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            sudo unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin
      - run:
          name: TF 13 Integration test
          command: make test
          no_output_timeout: 45m
      
      - run:
          name: Install Terraform 14
          command: |
            export TF_VERSION=0.14.4
            wget --quiet https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            sudo unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin
      - run:
          name: TF 14 Integration test
          command: make test
          no_output_timeout: 45m

orbs:
  go: circleci/go@0.2.0
  node: circleci/node@1.1.6
version: 2.1
workflows:
  default:
    jobs:
      - test:
          context: aws-ci-1
  version: 2
